# Etapa de build com SDK completo
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copia o csproj e restaura
COPY ["OrderManagementSystem.csproj", "./"]
RUN dotnet restore "OrderManagementSystem.csproj"

# Copia todo o restante
COPY . .
RUN dotnet publish "OrderManagementSystem.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Etapa final com o runtime ASP.NET
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app


# Copia os arquivos publicados
COPY --from=build /app/publish .

# Expõe a porta padrão
EXPOSE 8080

# Executa a aplicação
ENTRYPOINT ["dotnet", "OrderManagementSystem.dll"]
