name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ordermanagementsystem-464803 # Seu ID do projeto Google Cloud
  REGION: southamerica-east1              # Sua região do Cloud Run
  SERVICE_NAME: api                       # Nome do serviço no Cloud Run
  IMAGE_NAME: ordermanagementsystem       # Nome da sua imagem Docker (lowercase!)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Necessário para Workload Identity Federation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. Autenticação com o Google Cloud
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/107157443589/locations/global/workloadIdentityPools/marcos/providers/apiorders-github'
        # E-mail da Conta de Serviço:
        service_account: '107157443589-compute@developer.gserviceaccount.com'

    # 2. Configura Docker para fazer push para o Artifact Registry
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Docker to push to Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # 3. Build da Imagem Docker e Push para o Artifact Registry
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}

    # 4. Deploy da Imagem para o Cloud Run
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        project_id: ${{ env.PROJECT_ID }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}
        flags: '--allow-unauthenticated'
        
      
        
